# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed35c96a8d1a69540b2d420a5ebf1974e9a40a5dbd99c4fafd5baea8be6387566b08c1e65b93b486be890e86ab660dcae51ec72ecf72357d78674612554ee290

test:
  secret_key_base: f692672fd30b0669f3361145038e4596bd0627dbafcb9eca5ab95efa6763e111d16389a60fd6de7574e50f627cb4418cc27cf90d5d190935750a2f0b1adb2626

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
